In [1]:
import numpy as np

In [2]:
a=np.array([[1,6012],[2,7012],[3,6885],[4,7250],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

In [3]:
print(np.array(a))

[[   1 6012]
 [   2 7012]
 [   3 6885]
 [   4 7250]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [5]:
a[:,0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a[:,1]

array([6012, 7012, 6885, 7250, 4598, 5564, 6971, 7763, 8032, 9569])

In [7]:
a[:,1]+=2000

In [8]:
print(np.array(a))

[[    1  8012]
 [    2  9012]
 [    3  8885]
 [    4  9250]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [9]:
np.max(a[:,1])

np.int64(11569)

In [10]:
np.max(a)

np.int64(11569)

In [12]:
max_a=np.max(a)
max_a

np.int64(11569)

In [13]:
min_a=np.min(a)
min_a

np.int64(1)

In [14]:
a[:,1]>7000

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [15]:
[a[:,1]>7000]

[array([ True,  True,  True,  True, False,  True,  True,  True,  True,
         True])]

In [16]:
a[a[:,1]>7000]

array([[    1,  8012],
       [    2,  9012],
       [    3,  8885],
       [    4,  9250],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [27]:
np.sort(a[:,1])

array([ 6598,  7564,  8012,  8885,  8971,  9012,  9250,  9763, 10032,
       11569])

In [29]:
sorted_steps=np.sort(a[:,1])
sorted_steps

array([ 6598,  7564,  8012,  8885,  8971,  9012,  9250,  9763, 10032,
       11569])